# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nockstar-server
  namespace: minecraft
  labels:
    app: nockstar-server
spec:
  replicas: 1
  serviceName: nockstar-server
  selector:
    matchLabels:
      app: nockstar-server
  template:
    metadata:
      labels:
        app: nockstar-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: nockstar-data-pvc
      containers:
      - name: nockstar-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1.5Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: survival
          - name: MOTD
            value: Sixten, William, Edward och pappas server
          - name: ALLOW_FLIGHT
            value: 'TRUE'
          - name: OPS
            value: MuLvAd69
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30